name: Auto Restart Server
on:
  workflow_dispatch:
  schedule:
    # 17시부터 22시(UTC)까지 매시 정각에 실행
    - cron: "0 17-22 * * *"


jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: Restart CloudType Server
        run: |
          echo "Attempting to restart server..."
          echo "Current time: $(date)"
          response=$(curl -X PUT \
            "${{ secrets.CLOUDTYPE_API_URL }}" \
            -H "Authorization: Bearer ${{ secrets.CLOUDTYPE_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Origin: https://app.cloudtype.io" \
            -H "Referer: https://app.cloudtype.io/")
          echo "Response: $response"

      - name: Verify Server Status
        run: |
          echo "Waiting for server to start..."
          sleep 20  # 서버 시작 대기
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.SERVER_URL }}")
          echo "Server status code: $STATUS"
