name: Auto Restart Server
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17-22 * * *"

jobs:
  wake-up-server:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up server
        run: |
          echo "Attempting to wake up server..."
          echo "Current time: $(date)"
          curl -X GET ${{ secrets.SERVER_URL }}

      - name: Check server status
        run: |
          echo "Checking server status..."
          status_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.SERVER_URL }})
          echo "Server responded with status code: $status_code"
          if [ "$status_code" -eq 200 ] || [ "$status_code" -eq 302 ]; then
            echo "Server is up and running!"
          else
            echo "Warning: Server might not be responding correctly"
          fi
